[package]
name = "beluga"
version = "0.1.0"
authors = ["Johnny Lai <johnny.lai@me.com>"]

[dependencies]
base64 = "0.9.0"
getopts = "0.2"
handlebars = "0.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
sha1 = "0.6.0"

[[bin]]
name = "beluga"
path = "main.rs"
