images:
  devbase:
    tag: beluga-devbase:%s
    id_rsa: ~/.ssh/id_rsa
  testbase:
    tag: beluga-testbase:%s
    id_rsa: ~/.ssh/id_rsa
    from: devbase
commands:
  rspec:
    command: bundle exec rspec %s
    image: devbase
    extra_hosts:
      - "db:<%= host_public_ip %>"
  exec:
    command: "%s"
    image: devbase
    extra_hosts:
      - "db:<%= host_public_ip %>"
