FROM <%= ENV['DEVBASE_LABEL'] %>

RUN apt-get install -y Xvfb

RUN curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

RUN apt-get update && apt-get install -y google-chrome-stable
